name: Deploy Preview to Vercel

on:
  push:
    branches:
      - develop # Change this to your development branch if it's not 'develop'
  pull_request:
    branches:
      - develop # Trigger on pull requests to the develop branch

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Preview)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --pre --token $VERCEL_TOKEN
